name: Ace Fibreglass Roofing Limited
favicon: null
layout_spectrum: 0.520750748924911
typography_spectrum: 0.963331448379904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7644740857649595
  lightness: 0.5749519551172853
  saturation: 0.5799554951954633
  rhythmicContrast: 0.4907301547937095
purpose: []
